import { CampaignScenario } from '@/types/campaign';

export const generateScenarios = (): CampaignScenario[] => {
  return [
    {
      id: '1',
      name: 'Diwali Campaign 2025 Scenario 1',
      festivalDate: new Date('2025-10-20'),
      startDate: new Date('2025-09-01'),
      endDate: new Date('2025-10-31'),
      status: 'inactive',
      remarks: 'Conservative approach with 4 tiers',
      pools: [
        {
          id: '1',
          poolName: 'Pool 1 - Donors donated > 1lac',
          gifts: ['Premium Gift Set', 'Deluxe Hamper'],
          filtersApplied: 'Donation Amount: >₹1,00,000',
          filterDetails: {} as any,
          donorCount: 2500,
          remarks: 'Top tier donors',
          deliveryMethod: 'hand-delivery',
          createdAt: new Date(),
        },
        {
          id: '2',
          poolName: 'Pool 2 - Donors 25k to 1lac',
          gifts: ['Standard Gift Set'],
          filtersApplied: 'Donation Amount: ₹25,000-₹1,00,000',
          filterDetails: {} as any,
          donorCount: 8500,
          remarks: 'Mid-high tier',
          deliveryMethod: 'dispatch-bhishma',
          createdAt: new Date(),
        },
        {
          id: '3',
          poolName: 'Pool 3 - Donors 10k-25k',
          gifts: ['Basic Gift Set'],
          filtersApplied: 'Donation Amount: ₹10,000-₹25,000',
          filterDetails: {} as any,
          donorCount: 12000,
          remarks: 'Mid tier',
          deliveryMethod: 'dispatch-bhishma',
          createdAt: new Date(),
        },
        {
          id: '4',
          poolName: 'Pool 4 - Donors 3k to 10k',
          gifts: ['Token Gift'],
          filtersApplied: 'Donation Amount: ₹3,000-₹10,000',
          filterDetails: {} as any,
          donorCount: 18000,
          remarks: 'Entry tier',
          deliveryMethod: 'dispatch-bhishma',
          createdAt: new Date(),
        },
      ],
      createdAt: new Date(),
    },
    {
      id: '2',
      name: 'Diwali Campaign 2025 Scenario 2',
      festivalDate: new Date('2025-10-20'),
      startDate: new Date('2025-09-01'),
      endDate: new Date('2025-10-31'),
      status: 'inactive',
      remarks: 'Aggressive approach with 3 tiers only',
      pools: [
        {
          id: '1',
          poolName: 'Premium Donors - >50k',
          gifts: ['Luxury Gift Set', 'Premium Hamper', 'Special Token'],
          filtersApplied: 'Donation Amount: >₹50,000',
          filterDetails: {} as any,
          donorCount: 15000,
          remarks: 'Combined high value segment',
          deliveryMethod: 'hand-delivery',
          createdAt: new Date(),
        },
        {
          id: '2',
          poolName: 'Standard Donors - 10k-50k',
          gifts: ['Standard Gift Set'],
          filtersApplied: 'Donation Amount: ₹10,000-₹50,000',
          filterDetails: {} as any,
          donorCount: 20000,
          remarks: 'Mid tier combined',
          deliveryMethod: 'dispatch-bhishma',
          createdAt: new Date(),
        },
        {
          id: '3',
          poolName: 'Entry Donors - 3k-10k',
          gifts: ['Token Gift'],
          filtersApplied: 'Donation Amount: ₹3,000-₹10,000',
          filterDetails: {} as any,
          donorCount: 18000,
          remarks: 'Entry tier',
          deliveryMethod: 'dispatch-bhishma',
          createdAt: new Date(),
        },
      ],
      createdAt: new Date(),
    },
  ];
};
